// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfHMU2CKy9i5oRu56T8GeAaXbjVSAeJ-E',
    appId: '1:410286602822:web:5fec2484c85015ab76a847',
    messagingSenderId: '410286602822',
    projectId: 'expense-tracker-2afb7',
    authDomain: 'expense-tracker-2afb7.firebaseapp.com',
    storageBucket: 'expense-tracker-2afb7.firebasestorage.app',
    measurementId: 'G-T3BVVVMRQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDETbnx81n95xzScXSZICEaIQfvSa_ocfA',
    appId: '1:410286602822:android:bf4b21738b8cdbc676a847',
    messagingSenderId: '410286602822',
    projectId: 'expense-tracker-2afb7',
    storageBucket: 'expense-tracker-2afb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU7scrMMZPZQiW1EXm1nwIfA5MOwvfo-U',
    appId: '1:410286602822:ios:ef6130663866639a76a847',
    messagingSenderId: '410286602822',
    projectId: 'expense-tracker-2afb7',
    storageBucket: 'expense-tracker-2afb7.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU7scrMMZPZQiW1EXm1nwIfA5MOwvfo-U',
    appId: '1:410286602822:ios:ef6130663866639a76a847',
    messagingSenderId: '410286602822',
    projectId: 'expense-tracker-2afb7',
    storageBucket: 'expense-tracker-2afb7.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfHMU2CKy9i5oRu56T8GeAaXbjVSAeJ-E',
    appId: '1:410286602822:web:c4fd52e71af0fec776a847',
    messagingSenderId: '410286602822',
    projectId: 'expense-tracker-2afb7',
    authDomain: 'expense-tracker-2afb7.firebaseapp.com',
    storageBucket: 'expense-tracker-2afb7.firebasestorage.app',
    measurementId: 'G-PFP0WFS2YL',
  );
}
